steps:
- id: build builder
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/${_BUILDER_IMAGE}'
  - '-f'
  - 'Dockerfile.builder'
  - '.'

- id: build artifact
  name: 'gcr.io/$PROJECT_ID/${_BUILDER_IMAGE}'
  entrypoint: bash
  args:
  - '-c'
  - |
    make all DOCKER_TAG=${_APP_IMAGE}:0.0.0

images:
- 'gcr.io/$PROJECT_ID/reports-backend'

substitutions:
  _APP_IMAGE: reports-backend
  _BUILDER_IMAGE: reports-backend-builder
